spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_itboot?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
     ddl-auto: update
    show-sql: true
    open-in-view: false
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false
  resources:
    chain:
      strategy:
        content:
          enabled: false
          paths: /**
  mvc:
    static-path-pattern: /static/**
server:
  port: 8081
  tomcat:
    uri-encoding: UTF-8
    threads:
      min-spare: 20
      max: 100
    connection-timeout: 5000


